// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtbXquiq6yST_uwxtAVPQsuKkQO7XLU2s',
    appId: '1:583534812805:web:280ad5854a442d393ed3ec',
    messagingSenderId: '583534812805',
    projectId: 'newpro-77ff3',
    authDomain: 'newpro-77ff3.firebaseapp.com',
    storageBucket: 'newpro-77ff3.firebasestorage.app',
    measurementId: 'G-R53CZ8R471',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADqXH86uy8Yf4bdcSpwVweBVpAmElWVC4',
    appId: '1:583534812805:android:4f0529233afd52ea3ed3ec',
    messagingSenderId: '583534812805',
    projectId: 'newpro-77ff3',
    storageBucket: 'newpro-77ff3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5l7B4vRnvHYp7GDlmiC0Fh_P7Ar49Mgk',
    appId: '1:583534812805:ios:3d809791f3a2b28b3ed3ec',
    messagingSenderId: '583534812805',
    projectId: 'newpro-77ff3',
    storageBucket: 'newpro-77ff3.firebasestorage.app',
    iosBundleId: 'com.example.authFeature10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5l7B4vRnvHYp7GDlmiC0Fh_P7Ar49Mgk',
    appId: '1:583534812805:ios:3d809791f3a2b28b3ed3ec',
    messagingSenderId: '583534812805',
    projectId: 'newpro-77ff3',
    storageBucket: 'newpro-77ff3.firebasestorage.app',
    iosBundleId: 'com.example.authFeature10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtbXquiq6yST_uwxtAVPQsuKkQO7XLU2s',
    appId: '1:583534812805:web:b9b1a932b2e191b03ed3ec',
    messagingSenderId: '583534812805',
    projectId: 'newpro-77ff3',
    authDomain: 'newpro-77ff3.firebaseapp.com',
    storageBucket: 'newpro-77ff3.firebasestorage.app',
    measurementId: 'G-4R15PS404H',
  );
}
